window.goods = {
    'Tabacs': [
        {id: 129, label: 'Camel 400',price: 55.0},
        {id: 130, label: 'Marlboro 200',price: 33.0},
        {id: 131, label: 'Marlboro 400',price: 60.0},
        {id: 132, label: 'Marlb.Light200', full_label: 'Marlboro Light 200', price: 33.0},
        {id: 133, label: 'Marlb.Light400', full_label: 'Marlboro Light 400', price: 60.0}
    ],
    'Alcools': [
        {id: 0, label: 'JWalker 100cl', full_label: 'Johnnie Walker Red Label 100cl', price: 16.0},
        {id: 1, label: 'Ricard 1 Litre', price: 16.0},
        {id: 2, label: 'Biere Heineken', full_label: 'Biere Heineken 33cl', price: 0.0},
        {id: 3, label: 'Vin Rouge Gail', full_label: 'Vin Rouge Gaillac 18.7cl', price: 0.0},
        {id: 4, label: 'Vin Blanc Gail', full_label: 'Vin Blanc Gaillac 18.7cl', price: 0.0},
        {id: 5, label: 'Whisky JW 5cl', full_label: 'Johnny Walker Red Label 5cl', price: 0.0},
        {id: 6, label: 'Vodka Absolut', full_label: 'Vodka Absolut 5cl', price: 0.0},
        {id: 7, label: 'Champagne Dumo', full_label: 'Champagne Dumont 37.5cl', price: 0.0}
    ],
    'Parfums Femme': [
        {id: 78, label: 'Ck One Edt 100', full_label: 'Ck One Edt 100ml', price: 0.0},
        {id: 79, label: 'Coffret DIOR', full_label: 'Coffret Les Parfums De Dior', price: 0.0},
        {id: 80, label: 'J Adore', price: 0.0},
        {id: 81, label: 'Miss Dior Cher', full_label: 'Miss Dior Cherie Edt 50ml', price: 0.0},
        {id: 82, label: 'Angel Star In', full_label: 'Angel Star In The Sky', price: 0.0},
        {id: 83, label: 'Shalimar', full_label: 'Shalimar', price: 0.0},
        {id: 84, label: 'Organza', price: 0.0},
        {id: 85, label: 'IRRESISTIBLE G', full_label: 'Very Irresistible Givenchy', price: 0.0},
        {id: 86, label: 'Coffr. 5 Kenzo', full_label: 'Coffret 5 Miniatures Kenzo', price: 0.0},
        {id: 87, label: 'Summer Fragran', full_label: 'Flowerbykenzo Summer Fragrance', price: 0.0},
        {id: 88, label: 'Coffret Lolita', price: 0.0},
        {id: 89, label: 'Lolita Lempick', full_label: 'Lolita Lempicka', price: 0.0},
        {id: 90, label: 'Lady Million', full_label: 'Lady Million Edp 50ml', price: 0.0},
        {id: 91, label: 'Ricci Ricci Ed', full_label: 'Ricci Ricci Edp 50ml', price: 0.0},
        {id: 92, label: 'Parisienne', full_label: 'Parisienne Edp 50ml', price: 0.0},
        {id: 93, label: 'Acqua Di Gioia', full_label: 'Acqua Di Gioia Edp 50ml', price: 0.0},
        {id: 94, label: 'O De Lancome', full_label: 'O De Lancome Edt 75ml', price: 0.0},
        {id: 95, label: 'Fuel Pour Elle', full_label: 'Fuel For Life Pour Elle Edp50m', price: 0.0},
        {id: 96, label: 'Tresor In Love', full_label: 'Tresor In Love Edp V50ml', price: 0.0},
        {id: 97, label: 'Belle D Opium', full_label: 'Belle D Opium Ysl Edp 50ml', price: 0.0},
        {id: 98, label: 'Love Chloe Edp', full_label: 'Love Chloe Edp 50ml', price: 0.0},
        {id: 99, label: 'Idylle Edt 50m', full_label: 'Idylle Edt 50m', price: 0.0},
        {id: 100, label: 'Boss Orange', full_label: 'Hugo Boss Orange Woman Edt50ml', price: 0.0},
        {id: 101, label: 'Womanity Edp50', full_label: 'Womanity Edp 50ml', price: 0.0},
        {id: 102, label: 'Hello Kitty', full_label: 'Hello Kitty Edt 60ml', price: 0.0},
        {id: 103, label: 'Guerlain Homme', full_label: 'Guerlain Homme Edt 50ml', price: 0.0}
    ],
    'Parfums Homme': [
        {id: 104, label: 'Azzaro 50ml', price: 0.0},
        {id: 105, label: 'Booster 75ml', full_label: 'Booster Edt 75ml', price: 0.0},
        {id: 106, label: 'D&G for men 50', full_label: 'D & G The One For Men Edt 50ml', price: 0.0},
        {id: 107, label: 'Hugo 100ml', full_label: 'Hugo Edt 100ml', price: 0.0},
        {id: 108, label: 'Kenzo H 50ml', full_label: 'Kenzo Homme Edt 50ml', price: 0.0},
        {id: 109, label: 'Eau Masculin', full_label: 'Eau Au Masculin', price: 0.0},
        {id: 110, label: 'Fuel H 50ml', full_label: 'Fuel For Life Pour Lui 50ml', price: 0.0},
        {id: 111, label: 'Foot De Rue', price: 0.0},
        {id: 112, label: 'Black Xs 100ML', full_label: 'Black Xs Edt 100ml', price: 0.0},
        {id: 113, label: 'One Million', full_label: 'One Million Paco Rabanne', price: 0.0},
        {id: 114, label: 'Homme YSL 60ml', full_label: 'L Homme Ysl Edt 60ml', price: 0.0},
        {id: 115, label: 'Aqua Di Gio Ar', full_label: 'Acqua Di Gio Armani Edt 50ml', price: 0.0},
        {id: 116, label: 'Dior Homme Spo', full_label: 'Dior Homme Sport 50ml', price: 0.0},
        {id: 117, label: 'La Nuit De L H', full_label: 'La Nuit De L Homme Edt 60ml', price: 0.0},
        {id: 118, label: 'Boss Bottled', full_label: 'Hugo Boss Bottled Edt 50ml', price: 0.0}
    ],
    'Cosmetiques': [
        {id: 45, label: 'Tan Maximizer', full_label: 'Tan Maximizer 125ml Lancaster', price: 0.0},
        {id: 46, label: 'Capture', price: 0.0},
        {id: 47, label: 'Dior LIP MAX', full_label: 'Dior Addict Lip Maximizer', price: 0.0},
        {id: 48, label: 'Khol Terracott', full_label: 'Khol Terracotta', price: 0.0},
        {id: 49, label: 'PoudreTerra N1', full_label: 'Poudre Terracotta N1', price: 0.0},
        {id: 50, label: 'Mascara Phenom', full_label: 'Mascara Phenomen Eyes', price: 0.0},
        {id: 51, label: 'FR ManucureYSL', full_label: 'French Manucure Ysl', price: 0.0},
        {id: 52, label: 'Mascara Ysl', price: 0.0},
        {id: 53, label: 'Touche EclatN1', full_label: 'Touche Eclat N1', price: 0.0},
        {id: 54, label: 'Touche EclatN2', full_label: 'Touche Eclat N2', price: 0.0},
        {id: 55, label: 'PoudreTerra N2', full_label: 'Poudre Terracotta N2', price: 0.0},
        {id: 56, label: 'Poudre Terr N4', full_label: 'Poudre Terracotta N4', price: 0.0},
        {id: 57, label: 'Palette Terrac', full_label: 'Palette Terracotta', price: 0.0},
        {id: 58, label: 'Pinceau Magiqu', full_label: 'Pinceau Magique Tropiques Mine', price: 0.0},
        {id: 59, label: 'Coffret Clarin', full_label: 'Coffret Clarins Multi Active', price: 0.0}
    ],
    'Montres': [
        {id: 71, label: 'Fes.Mul.Dame B', full_label: 'Festina Multifonct.dame Blanc', price: 0.0},
        {id: 72, label: 'Fes.Mul.Hom.NO', full_label: 'Festina Multifonct.homme Noire', price: 0.0},
        {id: 73, label: 'Esprit Silver', full_label: 'Montre Esprit Silver Houston', price: 0.0},
        {id: 74, label: 'Sport Homme Bl', full_label: 'Festina Quartz Sport Homme Bla', price: 0.0},
        {id: 75, label: 'Fes.Mul.Dame.N', full_label: 'Festina Multifonction Dame Noi', price: 0.0},
        {id: 76, label: 'Fes.Mul.Homm.O', full_label: 'Festina Multifon. Homme Marron', price: 0.0},
        {id: 77, label: 'Sport.Hom.Noir', full_label: 'Festina Quartz Sport Homme Noi', price: 0.0}
    ],
    'Bijoux': [
        {id: 8, label: 'Swaro. COEUR', full_label: 'Pendentif Mini Coeur Swarovski', price: 0.0},
        {id: 9, label: 'Bra.Perle Gris', full_label: 'Bracelet Perle Gris Decibelle', price: 0.0},
        {id: 10, label: 'Bra.Perle Viol', full_label: 'Bracelet Perle Violet Decibell', price: 0.0},
        {id: 11, label: 'Collier 2 Sphe', full_label: 'Collier 2 Spheres', price: 0.0},
        {id: 12, label: 'Set 3 Bo Rhodi', full_label: 'Set 3 Bo Rhodium Decibelle', price: 0.0},
        {id: 13, label: 'Bague ARGENT', full_label: 'Bague Pilgrim New Silver Cryst', price: 0.0},
        {id: 14, label: 'Bague Purple', full_label: 'Bague Pilgrim New Silver Purpl', price: 0.0},
        {id: 15, label: 'B.O.Mod Set', full_label: 'Boucle D Oreilles Mod Set', price: 0.0}
    ],
    'Divers': [
        {id: 60, label: 'P-Clef Montre', full_label: 'Porte Clefs Montre Avion', price: 0.0},
        {id: 61, label: 'Q-snap WP800', full_label: 'Fuji Quicksnap Marine', price: 0.0},
        {id: 62, label: 'Sac Longchamp', full_label: 'Sac Voyage Longchamp', price: 0.0},
        {id: 63, label: 'Lunettes Fitne', full_label: 'Lunettes Fitness First Bronze', price: 0.0},
        {id: 64, label: 'Kit voyage', full_label: 'Kit De Voyage', price: 0.0},
        {id: 65, label: 'Travalo Pink', full_label: 'Travalo Atomizer Pink', price: 0.0},
        {id: 66, label: 'Travalo Silver', full_label: 'Travalo Atomizer Silver', price: 0.0},
        {id: 67, label: 'Porte Cle Enfa', full_label: 'Porte Cle Enfance Espoir', price: 0.0},
        {id: 68, label: 'Mini Speaker', full_label: 'Enceintes Miniatures', price: 0.0},
        {id: 69, label: 'Porte Clef FPO', full_label: 'Porte Clefs Europe Airpost', price: 0.0},
        {id: 70, label: 'Maquette FPO', price: 0.0}
    ],
    'Confiseries': [
        {id: 40, label: 'Toblerone 50g', price: 1.50},
        {id: 41, label: 'Toblerone 100g', price: 1.50},
        {id: 42, label: 'Kinder Bueno', price: 1.50},
        {id: 43, label: 'Haribo Dragibu', full_label: 'Haribo Dragibus 40g', price: 1.50},
        {id: 44, label: 'M & Ms Peanut', full_label: 'M & Ms Peanut 100g', price: 1.50}
    ],
    'Biscuits': [
        {id: 16, label: 'Croissant Frai', full_label: 'Croissant Frais', price: 0.0},
        {id: 17, label: 'Tranche De Cak', full_label: 'Tranche De Cake', price: 0.0},
        {id: 18, label: 'Gourde Compote', full_label: 'Gourde De Compote De Pommes', price: 0.0},
        {id: 19, label: 'Mini Brownies', full_label: 'Mini Brownies De Brossard', price: 0.0},
        {id: 20, label: 'Petit Ecolier', price: 0.0},
        {id: 21, label: 'MuffinFruitsR', full_label: 'Muffin Fruits Rouges', price: 0.0},
        {id: 22, label: 'Barre Cereales', full_label: 'Barre Cereales Special K', price: 0.0},
        {id: 23, label: 'Mikado 39g', price: 0.0},
        {id: 24, label: 'Paille d\'Or', price: 0.0}
    ],
    'Boisson Chaud': [
        {id: 25, label: 'D?caf?in?', full_label: 'D?caf?in? Stick', price: 0.0},
        {id: 26, label: 'Cappuccino', full_label: 'Cappuccino Stick', price: 0.0},
        {id: 27, label: 'Caf? Opercul?', price: 0.0},
        {id: 28, label: 'Chocolat Operc', full_label: 'Chocolat Opercul?', price: 0.0},
        {id: 29, label: 'Th? Opercul?', price: 0.0}
    ],
    'Boisson Fraich': [
        {id: 30, label: 'Cristaline50cl', full_label: 'Cristaline 50cl', price: 0.0},
        {id: 31, label: 'San Pellegrino', full_label: 'San Pellegrino 50cl', price: 0.0},
        {id: 32, label: 'Lipton Ice Tea', full_label: 'Lipton Ice Tea 33cl', price: 0.0},
        {id: 33, label: 'Orangina 33cl', price: 0.0},
        {id: 34, label: 'Tropicana 25cl', full_label: 'Tropicana, Jus D Orange 25cl', price: 0.0},
        {id: 35, label: 'Jus de Pomme', full_label: 'Tree Top, Jus De Pomme 33cl', price: 0.0},
        {id: 36, label: 'Smoothie Frais', full_label: 'My Smoothie Fraise 25cl', price: 0.0},
        {id: 37, label: 'Coca 33cl', price: 0.0},
        {id: 38, label: 'Coca Light 33c;', price: 0.0},
        {id: 39, label: 'My Smoothie Ma', full_label: 'My Smoothie Mangue', price: 0.0}
    ],
    'Sandwiches': [
        {id: 119, label: 'Poulet Halal', full_label: 'Sdw Club Poulet Halal', price: 0.0},
        {id: 120, label: 'Ciabatta Tomat', full_label: 'Sdw Ciabatta Tomate Mozzarella', price: 0.0},
        {id: 121, label: 'Baguette Froma', full_label: 'Sdw Baguette Fromage', price: 0.0},
        {id: 122, label: 'Sdw Wrap Dinde', full_label: 'Sdw Wrap Dinde Crudit?s', price: 0.0}
    ],
    'Snacks Sales': [
        {id: 123, label: 'Pik Et Croq', price: 0.0},
        {id: 124, label: 'Pringles Origi', full_label: 'Pringles Original', price: 0.0},
        {id: 124, label: 'Soupe Jap. FdM', full_label: 'Nouilles Japonaise Fruits De M', price: 0.0},
        {id: 124, label: 'Soupe Jap. Pou', full_label: 'Nouilles Japonnaises Poulet', price: 0.0},
        {id: 124, label: 'Cacahu?tes Gri', full_label: 'Cacahu?tes Grill?es 50g', price: 0.0},
        {id: 124, label: 'Biscuits Sal?s', full_label: 'Biscuits Sal?s', price: 0.0}
    ]
};